language: node_js
node_js:
- node
env:
  matrix:
  - PACKAGE=@digituz/react-button
  - PACKAGE=@digituz/react-input
  global:
    secure: Be6J9uK3v+ZkmL80j/9npqyKAg24zwUkZaz5bDDDFgPp8blS2vD+CL/i41XmBZDzvbj0yqPhOoYU/HVGF5avpzV4xWhgg8Z2/QaxpgFm1AmhiVUkVdmlb+ZECI6aDp9V/jSBHQRFReKe/UbTVhK+wFMB8zJkO+YxvF3L4hyWSNig9KXp2HeaebGUUiitBpsz1oxWc5p0a/Hkix7i2qr+jx2V7GZWh5D1n59HJFwU3InGNB1gbb+psa6gmR7ObX39Kn5fjTsb6Ui2CQAqcAuoDGKZO517t9GjfO5jNMjSE5GQxhXbToz3iS9a53JxR8v0ZMS5C8zlQalaWzNK0qmMKfTSMY2vfHvaiDowhNIdgKlyDeMb3FC83ck8UUtBMY1XhzUtr/PNpvOeTlwQht9XkaH+dnwdI29QvE28YuSgqDxv44KureCyX4igORxA6HD0HS0a7l+heWKcfc4CDNlrLNs/D5+jpB9Kx20O2wViTjUHeEjT/6xTNW8JHobFxKDGFMd3vpggeJPe68h8jQy3xr3BVcJCDm4gpzotWY1o6w2G5Lf6Lm2NQf4EoXdiuNlQ5tR8rD8ezCXLmTcRBduAZgMxfB/EsOIRTOSz9wP0ez1tCQ4nQZFT2gUUg1YZkV71TRK7Q+IXVJvMZDy1MTCChY0EaE3HiUahJFD3KIY67Nk=
before_script: lerna bootstrap
script: lerna run test --scope $PACKAGE
after_success:
- if [ -z "${TRAVIS_TAG}" ]; then exit 0; fi
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
- lerna exec --scope $PACKAGE -- npm publish
