language: node_js
node_js:
- node
env:
  matrix:
  - PACKAGE=Button
  - PACKAGE=Header
  - PACKAGE=Input
  - PACKAGE=InputLabel
  global:
  - secure: gs0W1eGlExhbKNha2UMJMzzVV2QbF1SlxWN6TG0gh55vI4q7RmIGYo3yVlgmx4fk/dl5yHQqhtKnHJcXvYlvju8hMu+8PFilzp+rhCe5eox5f9Hhu2y9llAeX1KTJ24/5VsyDuM528q+V1pbELLCY2Sr5gCaXozCgTR1604X6bJHtC6f4Q/wQ7wZaoo08Ahx08xSeFrpfTAbv4x7EK6aiz42uhyLGy1kNa2yxH0fAsMZ13Al/C4/ectjlC5uS6C9Fuh+MZzqzmyk4DeO8W2JSbI5auwE6BTHInr7E/ncoBY58dHiv6ISP6ikWFvsFZ3MicxoXclYZWjzRedW+Uo893ABX73T+fIQzGaMTFX+MMmvBYK5Lio8sUrT2LHJnxdVvyol+XqGkTLLCAKX5J6SML2m6pJtllzKapPM8pG51X9+BUDRb7Y6NzD3R8WUBMgT9qi3CH4WbhkeJU/T8N7y3au6QJNPX5PtCC7s8txnz9QQWM3FN1DPSjAcTDJdx27j2yAq/LwI3CrPob4wsxY1T3GEdCfwOrgN8zhAPU2B4xdt+5JpyTlyhAa54L2JMMmS3D8Ibjrmus7IoRY/dwQDa8uodJDBIFV5EHmOt3PYs776Q5fMascYWQ+dylZZ6nLATVDvCzQHuLu/jCu34gGba9LOxa/k8CDbYP4naQmLlds=
before_script:
- cd src
- npm install
script:
- cd $PACKAGE
- npm test
after_success:
- if [ -z "${TRAVIS_TAG}" ]; then exit 0; fi
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
- npm whoami
- pwd
- npm publish
